version: '3.4'
networks:
  grupoum:
volumes:
  keycloak-data:
    external: true
services:
  oauth:
    container_name: oauth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - SERVER_PORT=80
      - LOGGING_LEVEL=INFO
      - KEYCLOAK_REALM=master
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_CLIENT_ID=client-id
      - KEYCLOAK_CLIENT_SECRET=client-secret
    networks:
      - grupoum
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090/auth
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - grupoum