server:
  port: ${SERVER_PORT:80}

logging:
  level:
    root: INFO
    constsw:
      grupoum:
        oauth: ${LOGGING_LEVEL:INFO}
  file:
    name: log.log
    pattern: log.%d{yyyy-MM-dd}.log
    max-history: 10

integration:
  keycloak:
    realm: ${KEYCLOAK_REALM:master}
    url: ${KEYCLOAK_URL:http://localhost:8090/auth}
    client-id: ${KEYCLOAK_CLIENT_ID:client-id}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:secret}

